org: taleas1
app: interio

service: interio-service
provider:
  name: aws
  runtime: nodejs16.x 
  stage: dev
  region: eu-central-1
  memorySize: 128

  environment:
    MONGODB_URI: ${env:MONGODB_URI} 

# package:
#   include:
#     - models/**
#     - configurations/**
#     - handlers/**

functions:
  getUser:
    handler: handlers/user/getUserById.handler
    events:
      - http:
          path: /user/{id}
          method: GET
          cors: true
  createUser:
    handler: handlers/user/createUser.handler
    events:
      - http:
          path: /user
          method: POST
          cors: true
  deleteUser:
    handler: handlers/user/deleteUser.handler
    events:
      - http:
          path: /user/{id}
          method: DELETE
          cors: true
  getUserName:
    handler: handlers/user/getUserByName.handler
    events:
      - http:
          path: /user/search
          method: GET
          cors: true
  updateUser:
    handler: handlers/user/updateUser.handler
    events:
      - http:
          path: /user/{id}
          method: PUT
          cors: true
  getBusinessById:
    handler: handlers/business/getBusinessById.handler
    events:
      - http:
          path: /business/{id}
          method: GET
          cors: true
  createBusiness:
    handler: handlers/business/createBusiness.handler
    events:
      - http:
          path: /business
          method: POST
          cors: true
  deleteBusiness:
    handler: handlers/business/deleteBusiness.handler
    events:
      - http:
          path: /business/{id}
          method: DELETE
          cors: true
  getBusinessName:
    handler: handlers/business/getBusinessByName.handler
    events:
      - http:
          path: /business/search
          method: GET
          cors: true
  updateBusiness:
    handler: handlers/business/updateBusiness.handler
    events:
      - http:
          path: /business/{id}
          method: PUT
          cors: true
  getPostById:
    handler: handlers/post/getPostById.handler
    events:
      - http:
          path: /post/{id}
          method: GET
          cors: true
  createPost:
    handler: handlers/post/createPost.handler
    events:
      - http:
          path: /post
          method: POST
          cors: true
  deletePost:
    handler: handlers/post/deletePost.handler
    events:
      - http:
          path: /post/{id}
          method: DELETE
          cors: true
  getFiltredPosts:
    handler: handlers/post/getFilteredPosts.handler
    events:
      - http:
          path: /post/filtred
          method: GET
          cors: true
  getAvailablePosts:
    handler: handlers/post/getAvailablePosts.handler
    events:
      - http:
          path: /post/available
          method: GET
          cors: true
  createOffer:
    handler: handlers/offer/createOffer.handler
    events:
      - http:
          path: /offer
          method: POST
          cors: true
  deleteOffer:
    handler: handlers/offer/deleteOffer.handler
    events:
      - http:
          path: /offer/{id}
          method: DELETE
          cors: true
  getOfferById:
    handler: handlers/offer/getOfferById.handler
    events:
      - http:
          path: /offer/{id}
          method: GET
          cors: true
  createCategory:
    handler: handlers/categories/createCategory.handler
    events:
      - http:
          path: /category
          method: POST
          cors: true
  deleteCategory:
    handler: handlers/categories/deleteCategory.handler
    events:
      - http:
          path: /category/{id}
          method: DELETE
          cors: true
  getCategoryById:
    handler: handlers/categories/getCategoryById.handler
    events:
      - http:
          path: /category/{id}
          method: GET
          cors: true
  getAllCategories:
    handler: handlers/categories/getAllCategories.handler
    events:
      - http:
          path: /category/all
          method: GET
          cors: true
  createJob:
    handler: handlers/finishedJobs/createJob.handler
    events:
      - http:
          path: /finishedJobs
          method: POST
          cors: true
  getJobById:
    handler: handlers/finishedJobs/getJobById.handler
    events:
      - http:
          path: /finishedJobs/{id}
          method: GET
          cors: true
  createComment:
    handler: handlers/comment/createComment.handler
    events:
      - http:
          path: /comment
          method: POST
          cors: true
  getCommentById:
    handler: handlers/comment/getCommentById.handler
    events:
      - http:
          path: /comment/{id}
          method: GET
          cors: true
  deleteComment:
    handler: handlers/comment/deleteComment.handler
    events:
      - http:
          path: /comment/{id}
          method: DELETE
          cors: true
  createMessage:
    handler: handlers/message/createMessage.handler
    events:
      - http:
          path: /message
          method: POST
          cors: true
  getMessageById:
    handler: handlers/message/getMessageById.handler
    events:
      - http:
          path: /message/{id}
          method: GET
          cors: true
  createNotification:
    handler: handlers/notification/createNotification.handler
    events:
      - http:
          path: /notification
          method: POST
          cors: true
  getNotificationById:
    handler: handlers/notification/getNotificationById.handler
    events:
      - http:
          path: /notification/{id}
          method: GET
          cors: true
  createSubscriptionPlan:
    handler: handlers/subscriptionPlan/createPlan.handler
    events:
      - http:
          path: /subscriptionPlan
          method: POST
          cors: true
  getSubscriptionPlan:
    handler: handlers/subscriptionPlan/getPlanById.handler
    events:
      - http:
          path: /subscriptionPlan/{id}
          method: GET
          cors: true
  getAllSubscriptionPlans:
    handler: handlers/subscriptionPlan/getAll.handler
    events:
      - http:
          path: /subscriptionPlan/all
          method: GET
          cors: true
  deleteSubscriptionPlan:
    handler: handlers/subscriptionPlan/deletePlan.handler
    events:
      - http:
          path: /subscriptionPlan/{id}
          method: DELETE
          cors: true
  createSubscriptionManager:
    handler: handlers/subscriptionManager/createManager.handler
    events:
      - http:
          path: /subscriptionManager
          method: POST
          cors: true
  getSubscriptionManager:
    handler: handlers/subscriptionManager/getManagerById.handler
    events:
      - http:
          path: /subscriptionManager/{id}
          method: GET
          cors: true
  updateSubscriptionManager:
    handler: handlers/subscriptionManager/updateManager.handler
    events:
      - http:
          path: /subscriptionManager/{id}
          method: PUT
          cors: true
  getAllSubscriptionManager:
    handler: handlers/subscriptionManager/getSubscriptionManager.handler
    events:
      - http:
          path: /subscriptionManager/all
          method: DELETE
          cors: true
  createPaymentTransaction:
    handler: handlers/paymentTransaction/createPayment.handler
    events:
      - http:
          path: /paymentTransaction
          method: POST
          cors: true
  getPaymentTransaction:
    handler: handlers/paymentTransaction/getPaymentById.handler
    events:
      - http:
          path: /paymentTransaction/{id}
          method: GET
          cors: true
  
  
  
 