org: taleas1
app: interio

service: interio-service
provider:
  name: aws
  runtime: nodejs16.x 
  stage: dev
  region: eu-central-1
  memorySize: 128

  environment:
    MONGODB_URI: ${env:MONGODB_URI} 

# package:
#   include:
#     - models/**
#     - configurations/**
#     - handlers/**

functions:
<<<<<<< Updated upstream
#   getUser:
#     handler: handlers/user/getUserById.handler
#     events:
#       - http:
#           path: /user/{id}
#           method: GET
#           cors: true
=======
  # getUser:
  #   handler: handlers/user/getUserById.handler
  #   events:
  #     - http:
  #         path: /user/{id}
  #         method: GET
  #         cors: true
>>>>>>> Stashed changes
  createUser:
    handler: handlers/user/createUser.handler
    events:
      - http:
          path: /user
          method: POST
          cors: true
  # deleteUser:
  #   handler: handlers/user/deleteUser.handler
  #   events:
  #     - http:
  #         path: /user/{id}
  #         method: DELETE
  #         cors: true
  # getUserName:
  #   handler: handlers/user/getUserByName.handler
  #   events:
  #     - http:
  #         path: /user/search
  #         method: GET
  #         cors: true
  # updateUser:
  #   handler: handlers/user/updateUser.handler
  #   events:
  #     - http:
  #         path: /user/{id}
  #         method: PUT
  #         cors: true
  # getBusinessById:
  #   handler: handlers/business/getBusinessById.handler
  #   events:
  #     - http:
  #         path: /bussiness/{id}
  #         method: GET
  #         cors: true
  # createBusiness:
  #   handler: handlers/business/createBusiness.handler
  #   events:
  #     - http:
  #         path: /business
  #         method: POST
  #         cors: true
  # deleteBusiness:
  #   handler: handlers/business/deleteBusiness.handler
  #   events:
  #     - http:
  #         path: /business/{id}
  #         method: DELETE
  #         cors: true
  # getBusinessName:
  #   handler: handlers/business/getBusinessByName.handler
  #   events:
  #     - http:
  #         path: /business/search
  #         method: GET
  #         cors: true
  # updateBusiness:
  #   handler: handlers/business/updateBusiness.handler
  #   events:
  #     - http:
  #         path: /business/{id}
  #         method: PUT
  #         cors: true
  # getPostById:
  #   handler: handlers/post/getPostById.handler
  #   events:
  #     - http:
  #         path: /post/{id}
  #         method: GET
  #         cors: true
  # createPost:
  #   handler: handlers/post/createPost.handler
  #   events:
  #     - http:
  #         path: /post
  #         method: POST
  #         cors: true
  # deletePost:
  #   handler: handlers/post/deletePost.handler
  #   events:
  #     - http:
  #         path: /post/{id}
  #         method: DELETE
  #         cors: true
  # getFiltredPosts:
  #   handler: handlers/post/getFiltredPosts.handler
  #   events:
  #     - http:
  #         path: /post/filtred
  #         method: GET
  #         cors: true
  # getAvailablePosts:
  #   handler: handlers/post/getOpenPosts.handler
  #   events:
  #     - http:
  #         path: /post/{id}
  #         method: GET
  #         cors: true